<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sml2" nsURI="http://br.ufes.inf.nemo/sml2" nsPrefix="sml2">
  <eClassifiers xsi:type="ecore:EEnum" name="AllenKind">
    <eLiterals name="before"/>
    <eLiterals name="after" value="1"/>
    <eLiterals name="meets" value="2"/>
    <eLiterals name="metBy" value="3"/>
    <eLiterals name="overlaps" value="4"/>
    <eLiterals name="overlappedBy" value="5"/>
    <eLiterals name="finishes" value="6"/>
    <eLiterals name="finishedBy" value="7"/>
    <eLiterals name="includes" value="8"/>
    <eLiterals name="during" value="9"/>
    <eLiterals name="starts" value="10"/>
    <eLiterals name="startedBy" value="11"/>
    <eLiterals name="coincides" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparativeKind">
    <eLiterals name="lessThan"/>
    <eLiterals name="lessThanEqual" value="1"/>
    <eLiterals name="greaterThan" value="2"/>
    <eLiterals name="greaterThanEqual" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TemporalKind">
    <eLiterals name="present"/>
    <eLiterals name="past" value="1" literal="past"/>
    <eLiterals name="any" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllenLink" eSuperTypes="#//FormalRelation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sourceIsSituation targetIsSituation"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="sourceIsSituation" value="self.source.oclIsKindOf(SituationParticipant)"/>
      <details key="targetIsSituation" value="self.target.oclIsKindOf(SituationParticipant)"/>
    </eAnnotations>
    <eAnnotations source="Comments">
      <details key="sourceIsSituation" value="The source of an AllenRelation must be a SituationParticipant"/>
      <details key="targetIsSituation" value="The target of an AllenRelation must be a SituationParticipant"/>
    </eAnnotations>
    <eOperations name="getSource" lowerBound="1" eType="#//SituationParticipant"/>
    <eOperations name="getTarget" lowerBound="1" eType="#//SituationParticipant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//AllenKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeLink" eSuperTypes="#//SituationTypeAssociation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sourceIsParticipant_Reference2 targetIsAttribute"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="sourceIsParticipant_Reference2" value="self.source.oclIsKindOf(Participant) or &#xD;&#xA;self.source.oclIsKindOf(ModeReference) or&#xD;&#xA;(self.source.oclIsKindOf(ReferenceNode) and &#xD;&#xA;&#x9;(self.source.oclAsType(ReferenceNode).reference.oclIsKindOf(Participant) or&#xD;&#xA;&#x9;(self.source.oclAsType(ReferenceNode).reference.oclIsKindOf(ModeReference))"/>
      <details key="targetIsAttribute" value="self.target.oclIsKindOf(AttributeReference)"/>
    </eAnnotations>
    <eAnnotations source="Comments">
      <details key="sourceIsParticipant_Reference2" value="The source of an AttributeLink must be a Participant, a ModeReference or a ReferenceNode, which in this case must be a reference to a Participant or a ModeReference"/>
      <details key="targetIsAttribute" value="The target of an AttributeLink must be an Attribute"/>
    </eAnnotations>
    <eOperations name="getEntity" lowerBound="1" eType="#//Node">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="self.source"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAttribute" lowerBound="1" eType="#//AttributeReference">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="self.target"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeReference" eSuperTypes="#//ReferableElement">
    <eOperations name="getEntity" lowerBound="1" eType="#//Node">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="AttributeLink.allInstances()->select(x | x.getAttribute() = self)->asOrderedSet()->at(1).getEntity()"/>
      </eAnnotations>
      <eAnnotations source="Comments">
        <details key="getEntity" value="Returns the Node that owns the AttributeReference."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//Quality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterizationLink" eSuperTypes="#//SituationTypeAssociation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sourceIsMode targetIsEntity_Reference sameEndsAsType3"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="sourceIsMode" value="self.source.oclIsKindOf(ModeReference)"/>
      <details key="targetIsEntity_Reference" value="self.target.oclIsKindOf(EntityParticipant) or &#xD;&#xA;(self.target.oclIsKindOf(ReferenceNode) and &#xD;&#xA;&#x9;(self.target.oclAsType(ReferenceNode).reference.oclIsKindOf(EntityParticipant))"/>
      <details key="sameEndsAsType3" value="self.type.oclAsType(RefOntoUML::Characterization).characterizing() = self.source.oclAsType(ModeReference).type and&#xD;&#xA;self.type.oclAsType(RefOntoUML::Characterization).characterized() = self.target.oclAsType(EntityParticipant).type"/>
    </eAnnotations>
    <eAnnotations source="Comments">
      <details key="sourceIsMode" value="The source of a CharacterizationLink must be a ModeReference"/>
      <details key="targetIsEntity_Reference" value="The target of a CharacterizationLink must be an EntityParticipant or a ReferenceNode, which in this case must be a reference to an EntityParticipant"/>
      <details key="sameEndsAsType3" value="A CharacterizationLink must connect the same entities as its Characterization does"/>
    </eAnnotations>
    <eOperations name="getMode" lowerBound="1" eType="#//ModeReference">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="self.source"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getCharacterized" lowerBound="1" eType="#//EntityParticipant">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="self.target"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//Characterization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparativeRelation" abstract="true"
      eSuperTypes="#//FormalRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContextFormalLink" eSuperTypes="#//FormalRelation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sameEndsAsType2"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="sameEndsAsType2" value="self.type.oclAsType(RefOntoUML::FormalAssociation).memberEnd->exists(x,y | x = self.source.type and y = self.target.type)"/>
    </eAnnotations>
    <eAnnotations source="Comments">
      <details key="sameEndsAsType2" value="A FormalLink must connect the same entities as its FormalAssociation does"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//FormalAssociation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalRelation" abstract="true" eSuperTypes="#//SituationTypeAssociation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityParticipant" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//ObjectClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EqualsLink" eSuperTypes="#//ComparativeRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//ReferableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
        upperBound="-1" eType="#//FunctionParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sourceIsFunction"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="sourceIsFunction" value="self.source.oclIsKindOf(Function)"/>
    </eAnnotations>
    <eAnnotations source="Comments">
      <details key="sourceIsFunction" value="The source of a FunctionParameter must be a Function"/>
    </eAnnotations>
    <eOperations name="getFunction" lowerBound="1" eType="#//Function">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="self.source"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstantiationLink" eSuperTypes="#//FormalRelation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sourceIsParticipant_Reference targetIsLiteral"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="sourceIsParticipant_Reference" value="self.source.oclIsKindOf(EntityParticipant) or self.source.oclIsKindOf(RelatorParticipant) or (self.source.oclIsKindOf(ReferenceNode) and (self.source.oclAsType(ReferenceNode).reference.oclIsKindOf(EntityParticipant) or self.source.oclAsType(ReferenceNode).reference.oclIsKindOf(RelatorParticipant)))"/>
      <details key="targetIsLiteral" value="self.target.oclIsKindOf(TypeLiteral) and self.target.oclAsType(TypeLiteral).type.oclIsKindOf(RefOntoUML::Class)"/>
    </eAnnotations>
    <eAnnotations source="Comments">
      <details key="sourceIsParticipant_Reference" value="The source of an Instantiation must be an EntityParticipant, a RelatorParticipant or a ReferenceNode, which in this case must be a reference to an EntityParticipant or RelatorParticipant"/>
      <details key="targetIsLiteral" value="The target of an Instantiation must be a TypeLiteral and its type must be a RefOntoUML::Class"/>
    </eAnnotations>
    <eOperations name="getSource" lowerBound="1" eType="#//Participant"/>
    <eOperations name="getTarget" lowerBound="1" eType="#//TypeLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Node #//SituationTypeElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MediationLink" eSuperTypes="#//SituationTypeAssociation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sourceIsRelator targetIsEntity sameEndsAsType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="sourceIsRelator" value="self.source.oclIsKindOf(RelatorParticipant)"/>
      <details key="targetIsEntity" value="self.target.oclIsKindOf(EntityParticipant)"/>
      <details key="sameEndsAsType" value="self.type.oclAsType(RefOntoUML::Mediation).relator() = self.source.oclAsType(RelatorParticipant).type and&#xD;&#xA;self.type.oclAsType(RefOntoUML::Mediation).mediated() = self.target.oclAsType(EntityParticipant).type"/>
    </eAnnotations>
    <eAnnotations source="Comments">
      <details key="sourceIsRelator" value="The source of a MediationLink must be a RelatorParticipant"/>
      <details key="targetIsEntity" value="The target of a MediationLink must be an EntityParticipant"/>
      <details key="sameEndsAsType" value="A MediationLink must connect the same entities as its Mediation does"/>
    </eAnnotations>
    <eOperations name="getRelator" lowerBound="1" eType="#//RelatorParticipant">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="self.source"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getEntity" lowerBound="1" eType="#//EntityParticipant">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="self.target"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//Mediation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModeReference" eSuperTypes="#//ReferableElement">
    <eOperations name="getEntity" lowerBound="1" eType="#//EntityParticipant">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="CharacterizationLink.allInstances()->select(x | x.getMode() = self)->asOrderedSet()->at(1).getCharacterized()"/>
      </eAnnotations>
      <eAnnotations source="Comments">
        <details key="getEntity" value="Returns the EntityParticipant that owns the ModeReference."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//Mode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eOperations name="sourceRelation" ordered="false" upperBound="-1" eType="#//SituationTypeAssociation">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="SituationTypeAssociation.allInstances()->select(r | r.source = self)"/>
      </eAnnotations>
      <eAnnotations source="Comments">
        <details key="sourceRelation" value="Gets all associations in which the node element is source"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="targetRelation" upperBound="-1" eType="#//SituationTypeAssociation">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="SituationTypeAssociation.allInstances()->select(r | r.target = self)"/>
      </eAnnotations>
      <eAnnotations source="Comments">
        <details key="targetRelation" value="Gets all associations in which the node element is target"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedComparativeLink" eSuperTypes="#//ComparativeRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ComparativeKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" abstract="true" eSuperTypes="#//ReferableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="maxGreatherThanMin"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="maxGreatherThanMin" value="if (self.upperBound &lt;> -1) then self.upperBound >= self.lowerBound else self.lowerBound &lt;> -1 endif"/>
    </eAnnotations>
    <eAnnotations source="Comments">
      <details key="maxGreatherThanMin" value="The maximum instances number of a Participant must be greather than or equal the minimum"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="immutable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isImageOf" eType="#//Participant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualityLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//ReferenceStructure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferableElement" abstract="true" eSuperTypes="#//Node #//SituationTypeElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="situation" lowerBound="1"
        eType="#//SituationParticipant" eOpposite="#//SituationParticipant/references"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//ReferableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelatorParticipant" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//Relator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelfReference" eSuperTypes="#//SituationParticipant"/>
  <eClassifiers xsi:type="ecore:EClass" name="SituationParticipant" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporality" lowerBound="1"
        eType="#//TemporalKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//ReferenceNode" containment="true" eOpposite="#//ReferenceNode/situation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//SituationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SituationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//SituationTypeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SituationTypeAssociation" abstract="true"
      eSuperTypes="#//SituationTypeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SituationTypeElement" abstract="true">
    <eOperations name="getSituation" lowerBound="1" eType="#//SituationType">
      <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
        <details key="body" value="SituationType.allInstances()->select(x | x.elements->exists(y | y = self))->asOrderedSet()->at(1)"/>
      </eAnnotations>
      <eAnnotations source="Comments">
        <details key="situation" value="Gets the SituationType that contains the SituationTypeElement"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMLModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//SituationType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextModel" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../br.ufes.inf.nemo.ontouml/model/RefOntoUML.ecore#//Class"/>
  </eClassifiers>
</ecore:EPackage>
