<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="z3py" nsURI="http://z3py/1.0" nsPrefix="z3py">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="FunctionCallNumberOfArguments"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="FunctionCallNumberOfArguments" value="self.calledFunction.numberOfArguments = self.arguments->size()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledFunction" lowerBound="1"
        eType="#//BooleanFunctionDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false"
        unique="false" lowerBound="1" upperBound="-1" eType="#//IntConstant" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quantification" abstract="true" eSuperTypes="#//Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="IrreflexiveQuant"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="IrreflexiveQuant" value="self.expression &lt;> self"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quantifiesOver" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//IntConstant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniversalQuantification" eSuperTypes="#//Quantification"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExistentialQuantification" eSuperTypes="#//Quantification"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conjunction" eSuperTypes="#//LogicalBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Disjunction" eSuperTypes="#//LogicalBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveDisjunction" eSuperTypes="#//LogicalBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalNegation" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implication" eSuperTypes="#//LogicalBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiImplication" eSuperTypes="#//LogicalBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalBinaryExpression" abstract="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand1" lowerBound="1"
        eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand2" lowerBound="1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanFunctionDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfArguments" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntConstant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OntoUMLZ3System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" lowerBound="1"
        upperBound="-1" eType="#//BooleanFunctionDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" lowerBound="1"
        upperBound="-1" eType="#//IntConstant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formulas" lowerBound="1"
        upperBound="-1" eType="#//Quantification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equality" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand1" lowerBound="1"
        eType="#//IntConstant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand2" lowerBound="1"
        eType="#//IntConstant"/>
  </eClassifiers>
</ecore:EPackage>
