<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="defaultname" nsURI="http://defaultname/1.0" nsPrefix="defaultname">
  <eClassifiers xsi:type="ecore:EClass" name="EClass0">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="alias" value="John"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calend" upperBound="-1"
        eType="#//Calendar">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="namespace" value="kmkm"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass1" eSuperTypes="#//EClass0">
    <eAnnotations source="oaifaodifjad" references="#//EClass1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dois" eType="#//EClass2"
        eOpposite="#//EClass2/um"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="um" eType="#//EClass1"
        eOpposite="#//EClass1/dois"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Calendar" instanceClassName="java.util.Calendar"/>
</ecore:EPackage>
